/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package videojuego;

import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.Int;
import javax.swing.JOptionPane;

/**
 *
 * @author chumo
 */
public class Pelea extends javax.swing.JFrame {

    /**
     * Creates new form Pelea
     */
    public Pelea() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblbatista = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblwarripr1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblvida = new javax.swing.JLabel();
        btnGolpe = new javax.swing.JButton();
        btnPatada = new javax.swing.JButton();
        lblvidabatista1 = new javax.swing.JLabel();
        jblvidabatista = new javax.swing.JLabel();
        btnlanza = new javax.swing.JButton();
        btnBombazo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblbatista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/videojuego/batista.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setText("VS.");

        lblwarripr1.setIcon(new javax.swing.ImageIcon("C:\\Users\\chumo\\Pictures\\Warrior.png")); // NOI18N

        jLabel2.setText("Vida del guerrero");

        lblvida.setText("100");

        btnGolpe.setText("Golpe");
        btnGolpe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGolpeActionPerformed(evt);
            }
        });

        btnPatada.setText("Patada");
        btnPatada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatadaActionPerformed(evt);
            }
        });

        lblvidabatista1.setText("Vida Batista");

        jblvidabatista.setText("100");

        btnlanza.setText("Lanza");
        btnlanza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlanzaActionPerformed(evt);
            }
        });

        btnBombazo.setText("Bombazo");
        btnBombazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBombazoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(lblbatista)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblvida, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jblvidabatista)
                        .addGap(39, 39, 39)
                        .addComponent(lblvidabatista1)
                        .addGap(81, 81, 81))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGolpe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPatada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnlanza)
                        .addGap(18, 18, 18)
                        .addComponent(btnBombazo)
                        .addGap(71, 71, 71))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(51, 51, 51)
                    .addComponent(lblwarripr1)
                    .addContainerGap(363, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblvida)
                    .addComponent(lblvidabatista1)
                    .addComponent(jblvidabatista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGolpe)
                    .addComponent(btnPatada)
                    .addComponent(btnlanza)
                    .addComponent(btnBombazo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(252, 252, 252))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 79, Short.MAX_VALUE)
                .addComponent(lblbatista, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(64, Short.MAX_VALUE)
                    .addComponent(lblwarripr1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(15, 15, 15)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public int vidawarr=100,vidabatista;
public String vida;
void ganar()
{
 if(vidabatista<=0)
        {
          JOptionPane.showMessageDialog(this,"Tu rival a Perdido");
          JOptionPane.showMessageDialog(this,"Has ganado");
        }
}
    private void btnGolpeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGolpeActionPerformed
        // TODO add your handling code here:
        vida=jblvidabatista.getText();         
        vidabatista=Integer.parseInt(vida); 
        JOptionPane.showMessageDialog(this,"Batista ha sido golpeado");
        vidabatista=vidabatista-10;
        vida=String.valueOf(vidabatista);
        jblvidabatista.setText(vida);
        ganar();
 
    }//GEN-LAST:event_btnGolpeActionPerformed

    private void btnPatadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatadaActionPerformed
        vida=jblvidabatista.getText();         
        vidabatista=Integer.parseInt(vida); 
        JOptionPane.showMessageDialog(this,"Batista ha recibido una patada voladora");
        vidabatista=vidabatista-45;
        vida=String.valueOf(vidabatista);
        jblvidabatista.setText(vida);
        ganar();

    }//GEN-LAST:event_btnPatadaActionPerformed

    private void btnlanzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlanzaActionPerformed
       vida=lblvida.getText();         
        vidabatista=Integer.parseInt(vida); 
        JOptionPane.showMessageDialog(this,"kazama ha recibido una lanza");
        vidawarr=vidawarr-20;
        vida=String.valueOf(vidawarr);
        lblvida.setText(vida);
        ganar();
    }//GEN-LAST:event_btnlanzaActionPerformed

    private void btnBombazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBombazoActionPerformed
        vida=lblvida.getText();         
        vidabatista=Integer.parseInt(vida); 
        JOptionPane.showMessageDialog(this,"Kazama ha recibido un bombazo");
        vidawarr=vidawarr-50;
        vida=String.valueOf(vidawarr);
        lblvida.setText(vida);
        ganar();

    }//GEN-LAST:event_btnBombazoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pelea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pelea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pelea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pelea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pelea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBombazo;
    private javax.swing.JButton btnGolpe;
    private javax.swing.JButton btnPatada;
    private javax.swing.JButton btnlanza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jblvidabatista;
    private javax.swing.JLabel lblbatista;
    private javax.swing.JLabel lblvida;
    private javax.swing.JLabel lblvidabatista1;
    private javax.swing.JLabel lblwarripr1;
    // End of variables declaration//GEN-END:variables
}
